name: Automation Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission for Gradle
        run: chmod +x gradlew

      # =====================
      # Install Chrome
      # =====================
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      # =====================
      # API TEST
      # =====================
      - name: Run API Test
        run: ./gradlew apiTest
        continue-on-error: true

      # =====================
      # WEB TEST
      # =====================
      - name: Run Web Test
        run: ./gradlew webTest
        continue-on-error: true

      # =====================
      # E2E TEST
      # =====================
      - name: Run E2E Test
        run: ./gradlew e2eTest --info
        continue-on-error: true

      # =====================
      # UPLOAD REPORT
      # =====================
      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-report
          path: |
            build/reports/
            reports/
